# Generated by Django 5.0.3 on 2024-04-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='dni',
            new_name='cuit',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='apellido',
            new_name='domicilio',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='rSocial',
        ),
    ]
