# Generated by Django 5.0.3 on 2024-04-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0003_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(),
        ),
    ]
