# Generated by Django 5.0.3 on 2024-04-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0004_alter_producto_precio_alter_producto_stock_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
