# Generated by Django 5.0.3 on 2024-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
